<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="fn" uri="jakarta.tags.functions" %>

<title>Lịch sử đơn hàng | Book Store</title>
<h1>Lịch sử đặt hàng</h1>
<c:if test="${not empty flashSuccess}"><div class="notice"><c:out value="${flashSuccess}"/></div></c:if><c:if test="${not empty flashError}"><div class="notice errorbox"><c:out value="${flashError}"/></div></c:if>
<form method="get" action="${fn:escapeXml(pageContext.request.contextPath)}/orders" class="actions filter-bar"><label for="status">Trạng thái</label><select id="status" name="status"><option value="ALL" ${fn:escapeXml(selectedStatus eq 'ALL' ? 'selected' : '')}>Tất cả</option><c:forEach var="s" items="${statuses}"><option value="${fn:escapeXml(s.code)}" ${fn:escapeXml(selectedStatus eq s.code ? 'selected' : '')}>${fn:escapeXml(s.label)}</option></c:forEach></select><button class="button">Lọc</button></form>
<c:choose><c:when test="${empty orders}"><section class="panel" style="margin-top:16px">Chưa có đơn hàng phù hợp.</section></c:when><c:otherwise><c:forEach var="order" items="${orders}"><section class="panel" style="margin-top:16px"><div class="actions"><h2>Đơn #${fn:escapeXml(order.orderId)}</h2><span class="tag">${fn:escapeXml(order.status.label)}</span></div><p class="meta">Ngày đặt: ${fn:escapeXml(order.createdAt)} · ${fn:escapeXml(order.paymentMethod)} · Tổng: ${fn:escapeXml(order.total)}</p><p><c:out value="${order.recipientName}"/> · <c:out value="${order.phone}"/><br><c:out value="${order.shippingAddress}"/><c:if test="${not empty order.note}"><br>Ghi chú: <c:out value="${order.note}"/></c:if></p><ul><c:forEach var="item" items="${order.items}"><li><c:out value="${item.bookTitle}"/> × ${fn:escapeXml(item.quantity)} — ${fn:escapeXml(item.lineTotal)}</li></c:forEach></ul></section></c:forEach></c:otherwise></c:choose>
<nav class="pager"><c:if test="${currentPage gt 1}"><a href="?status=${fn:escapeXml(selectedStatus)}&page=${fn:escapeXml(currentPage-1)}">Trước</a></c:if><c:forEach begin="1" end="${totalPages}" var="p"><c:choose><c:when test="${p eq currentPage}"><span class="active">${fn:escapeXml(p)}</span></c:when><c:otherwise><a href="?status=${fn:escapeXml(selectedStatus)}&page=${fn:escapeXml(p)}">${fn:escapeXml(p)}</a></c:otherwise></c:choose></c:forEach><c:if test="${currentPage lt totalPages}"><a href="?status=${fn:escapeXml(selectedStatus)}&page=${fn:escapeXml(currentPage+1)}">Sau</a></c:if></nav>
