<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<title>Quản lý đơn hàng</title>
<h1>Quản lý đơn hàng</h1>
<c:if test="${not empty flashSuccess}"><div class="notice"><c:out value="${flashSuccess}"/></div></c:if><c:if test="${not empty flashError}"><div class="notice errorbox"><c:out value="${flashError}"/></div></c:if>
<form method="get" action="${pageContext.request.contextPath}/admin/orders" class="actions"><label for="status">Trạng thái</label><select id="status" name="status"><option value="ALL" ${selectedStatus eq 'ALL' ? 'selected' : ''}>Tất cả</option><c:forEach var="s" items="${statuses}"><option value="${s.code}" ${selectedStatus eq s.code ? 'selected' : ''}>${s.label}</option></c:forEach></select><button class="button">Lọc</button></form>
<div class="table-wrap"><table class="admin-orders"><thead><tr><th>Đơn</th><th>Khách hàng</th><th>Sản phẩm</th><th>Ngày / Tổng</th><th>Trạng thái</th><th>Cập nhật</th></tr></thead><tbody>
<c:forEach var="order" items="${orders}"><tr><td>#${order.orderId}<br><small>${order.paymentMethod}</small></td><td><c:out value="${order.recipientName}"/><br><c:out value="${order.phone}"/><br><c:out value="${order.shippingAddress}"/><c:if test="${not empty order.note}"><br><c:out value="${order.note}"/></c:if></td><td><c:forEach var="item" items="${order.items}"><c:out value="${item.bookTitle}"/> × ${item.quantity}<br></c:forEach></td><td>${order.createdAt}<br><strong>${order.total}</strong></td><td>${order.status.label}</td><td><c:set var="targets" value="${transitions[order.orderId]}"/><c:if test="${not empty targets}"><form method="post" action="${pageContext.request.contextPath}/admin/orders"><input type="hidden" name="orderId" value="${order.orderId}"><input type="hidden" name="status" value="${selectedStatus}"><input type="hidden" name="page" value="${currentPage}"><select name="targetStatus"><c:forEach var="target" items="${targets}"><option value="${target.code}">${target.label}</option></c:forEach></select><button class="button">Cập nhật</button></form></c:if></td></tr></c:forEach>
</tbody></table></div>
<c:if test="${empty orders}"><p class="panel">Không có đơn hàng phù hợp.</p></c:if>
<nav class="pager"><c:if test="${currentPage gt 1}"><a href="?status=${selectedStatus}&page=${currentPage-1}">Trước</a></c:if><c:forEach begin="1" end="${totalPages}" var="p"><c:choose><c:when test="${p eq currentPage}"><span class="active">${p}</span></c:when><c:otherwise><a href="?status=${selectedStatus}&page=${p}">${p}</a></c:otherwise></c:choose></c:forEach><c:if test="${currentPage lt totalPages}"><a href="?status=${selectedStatus}&page=${currentPage+1}">Sau</a></c:if></nav>
